// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXLsU0JVUsZW8SB1Lc08b5AYAY_rg4Ptk',
    appId: '1:502267337175:web:8e45f34ba5eb1efe191392',
    messagingSenderId: '502267337175',
    projectId: 'bahanap-cc206',
    authDomain: 'bahanap-cc206.firebaseapp.com',
    storageBucket: 'bahanap-cc206.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqBzsdrfXS595GFY6tHjQmSwxYLIi1s6M',
    appId: '1:502267337175:android:eaaa3249149f5145191392',
    messagingSenderId: '502267337175',
    projectId: 'bahanap-cc206',
    storageBucket: 'bahanap-cc206.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8vwnWtGIs00pfulFCk4ekeqZHtNkw-kg',
    appId: '1:502267337175:ios:1fdb8122cb736de2191392',
    messagingSenderId: '502267337175',
    projectId: 'bahanap-cc206',
    storageBucket: 'bahanap-cc206.firebasestorage.app',
    iosBundleId: 'com.example.cc206Bahanap2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8vwnWtGIs00pfulFCk4ekeqZHtNkw-kg',
    appId: '1:502267337175:ios:1fdb8122cb736de2191392',
    messagingSenderId: '502267337175',
    projectId: 'bahanap-cc206',
    storageBucket: 'bahanap-cc206.firebasestorage.app',
    iosBundleId: 'com.example.cc206Bahanap2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXLsU0JVUsZW8SB1Lc08b5AYAY_rg4Ptk',
    appId: '1:502267337175:web:8dac8ffc73b32f4c191392',
    messagingSenderId: '502267337175',
    projectId: 'bahanap-cc206',
    authDomain: 'bahanap-cc206.firebaseapp.com',
    storageBucket: 'bahanap-cc206.firebasestorage.app',
  );
}
